#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use ConnectFour\Command\RunGameCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new RunGameCommand());
$application->run();